// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkXHVGIF22wv31C3Z5zUxd59qpywc_ItA',
    appId: '1:412848064485:web:67c6d9088320d64ef7110c',
    messagingSenderId: '412848064485',
    projectId: 'svareign-c8744',
    authDomain: 'svareign-c8744.firebaseapp.com',
    storageBucket: 'svareign-c8744.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKPaMOLi981i1k0iOnySkn8BsEypTK6jE',
    appId: '1:412848064485:android:d7c12e0122511db8f7110c',
    messagingSenderId: '412848064485',
    projectId: 'svareign-c8744',
    storageBucket: 'svareign-c8744.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0zwk-qKQZg7BBZ45VCaOEv0sfbRZAsls',
    appId: '1:412848064485:ios:1b66fe2b0144a9e7f7110c',
    messagingSenderId: '412848064485',
    projectId: 'svareign-c8744',
    storageBucket: 'svareign-c8744.firebasestorage.app',
    iosBundleId: 'com.example.svareign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0zwk-qKQZg7BBZ45VCaOEv0sfbRZAsls',
    appId: '1:412848064485:ios:1b66fe2b0144a9e7f7110c',
    messagingSenderId: '412848064485',
    projectId: 'svareign-c8744',
    storageBucket: 'svareign-c8744.firebasestorage.app',
    iosBundleId: 'com.example.svareign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkXHVGIF22wv31C3Z5zUxd59qpywc_ItA',
    appId: '1:412848064485:web:e040273191a8b5cdf7110c',
    messagingSenderId: '412848064485',
    projectId: 'svareign-c8744',
    authDomain: 'svareign-c8744.firebaseapp.com',
    storageBucket: 'svareign-c8744.firebasestorage.app',
  );
}
